export const GET_ALL_TASKS = 'GET_ALL_TASKS';
export const GET_ALL_TASKS_SUCCESS = 'GET_ALL_TASKS_SUCCESS';
export const GET_ALL_TASKS_FAIL = 'GET_ALL_TASKS_FAIL';

export const GET_TASK_DETAILS = 'GET_TASK_DETAILS';
export const GET_TASK_DETAILS_SUCCESS = 'GET_TASK_DETAILS_SUCCESS';
export const GET_TASK_DETAILS_FAIL = 'GET_TASK_DETAILS_FAIL';

export const CREATE_TASK = 'CREATE_TASK_DETAILS';
export const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS';
export const CREATE_TASK_FAIL = 'CREATE_TASK_FAIL';

export const CHANGE_TASK_STATUS = 'CHANGE_TASK_STATUS';
export const CHANGE_TASK_STATUS_SUCCESS = 'CHANGE_TASK_STATUS_SUCCESS';
export const CHANGE_TASK_STATUS_FAIL = 'CHANGE_TASK_STATUS_FAIL';
